"""empty message

Revision ID: 22743575e73f
Revises: fbbf788ab5e1
Create Date: 2025-12-05 23:22:31.464373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22743575e73f'
down_revision: Union[str, Sequence[str], None] = 'fbbf788ab5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('danger_level_cm', sa.Integer(), nullable=True))
    op.add_column('objects', sa.Column('actual_level_cm', sa.Integer(), nullable=True))
    op.add_column('objects', sa.Column('actual_discharge_m3s', sa.Integer(), nullable=True))
    op.add_column('objects', sa.Column('water_temperature_C', sa.Integer(), nullable=True))
    op.add_column('objects', sa.Column('water_object_code', sa.String(), nullable=True))
    op.alter_column('objects', 'region_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('objects', 'region_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('objects', 'water_object_code')
    op.drop_column('objects', 'water_temperature_C')
    op.drop_column('objects', 'actual_discharge_m3s')
    op.drop_column('objects', 'actual_level_cm')
    op.drop_column('objects', 'danger_level_cm')
    # ### end Alembic commands ###
