"""empty message

Revision ID: 36dccaf1901f
Revises: 9917ed85883c
Create Date: 2025-12-06 13:21:44.991338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36dccaf1901f'
down_revision: Union[str, Sequence[str], None] = '9917ed85883c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('water_classes', sa.Column('water_class', sa.Integer(), nullable=True))
    op.add_column('water_classes', sa.Column('location_info', sa.Text(), nullable=True))
    op.add_column('water_classes', sa.Column('purpose', sa.Text(), nullable=True))
    op.add_column('water_classes', sa.Column('fauna', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('water_classes', 'fauna')
    op.drop_column('water_classes', 'purpose')
    op.drop_column('water_classes', 'location_info')
    op.drop_column('water_classes', 'water_class')
    # ### end Alembic commands ###
