"""empty message

Revision ID: 42e48bbb14bd
Revises: c96248c1e6a2
Create Date: 2025-12-06 22:13:38.109474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e48bbb14bd'
down_revision: Union[str, Sequence[str], None] = 'c96248c1e6a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_table('histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('level_cm', sa.Integer(), nullable=True),
    sa.Column('discharge_m3s', sa.Float(), nullable=True),
    sa.Column('temperature_C', sa.Float(), nullable=True),
    sa.Column('status1', sa.Integer(), nullable=True),
    sa.Column('status2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_histories_id'), 'histories', ['id'], unique=False)
    op.create_table('water_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('water_class_id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['history_id'], ['histories.id'], ),
    sa.ForeignKeyConstraint(['water_class_id'], ['water_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_histories_id'), 'water_histories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_histories_id'), table_name='water_histories')
    op.drop_table('water_histories')
    op.drop_index(op.f('ix_histories_id'), table_name='histories')
    op.drop_table('histories')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
