"""empty message

Revision ID: 7c1c18368567
Revises: bc854e64e8d5
Create Date: 2025-12-06 22:33:58.406267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1c18368567'
down_revision: Union[str, Sequence[str], None] = 'bc854e64e8d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_group_number_code', 'groups', ['number', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_group_number_code', 'groups', type_='unique')
    # ### end Alembic commands ###
