"""empty message

Revision ID: 8a88daf2386e
Revises: 4e5a1aac4ddd
Create Date: 2025-12-07 10:37:36.634001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a88daf2386e'
down_revision: Union[str, Sequence[str], None] = '4e5a1aac4ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('water_classes', sa.Column('region_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'water_classes', 'regions', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'water_classes', type_='foreignkey')
    op.drop_column('water_classes', 'region_id')
    # ### end Alembic commands ###
