"""empty message

Revision ID: 920dee58a851
Revises: 
Create Date: 2025-12-05 15:55:46.772387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920dee58a851'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_types_id'), 'resource_types', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('guest', 'expert', name='user_role_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('water_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_types_id'), 'water_types', ['id'], unique=False)
    op.create_table('objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('resource_type_id', sa.Integer(), nullable=True),
    sa.Column('water_type_id', sa.Integer(), nullable=True),
    sa.Column('fauna', sa.Boolean(), nullable=True),
    sa.Column('passport_date', sa.Date(), nullable=True),
    sa.Column('technical_condition', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resource_types.id'], ),
    sa.ForeignKeyConstraint(['water_type_id'], ['water_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objects_id'), 'objects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_objects_id'), table_name='objects')
    op.drop_table('objects')
    op.drop_index(op.f('ix_water_types_id'), table_name='water_types')
    op.drop_table('water_types')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_resource_types_id'), table_name='resource_types')
    op.drop_table('resource_types')
    # ### end Alembic commands ###
