"""empty message

Revision ID: 9917ed85883c
Revises: 22743575e73f
Create Date: 2025-12-06 10:38:10.300759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9917ed85883c'
down_revision: Union[str, Sequence[str], None] = '22743575e73f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('index', sa.String(), nullable=True),
    sa.Column('parameter', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('concentration', sa.Float(), nullable=True),
    sa.Column('background', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_water_classes_id'), 'water_classes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_water_classes_id'), table_name='water_classes')
    op.drop_table('water_classes')
    # ### end Alembic commands ###
