"""empty message

Revision ID: c96248c1e6a2
Revises: 36dccaf1901f
Create Date: 2025-12-06 15:14:54.868040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c96248c1e6a2'
down_revision: Union[str, Sequence[str], None] = '36dccaf1901f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CAP_MCM', sa.Float(), nullable=True),
    sa.Column('CAP_MAX', sa.Float(), nullable=True),
    sa.Column('CAP_MIN', sa.Float(), nullable=True),
    sa.Column('AREA_SKM', sa.Float(), nullable=True),
    sa.Column('AREA_MAX', sa.Float(), nullable=True),
    sa.Column('DEPTH_M', sa.Float(), nullable=True),
    sa.Column('CATCH_SKM', sa.Float(), nullable=True),
    sa.Column('DIS_AVG_LS', sa.Float(), nullable=True),
    sa.Column('ELEV_MASL', sa.Float(), nullable=True),
    sa.Column('DAM_HGT_M', sa.Float(), nullable=True),
    sa.Column('DAM_LEN_M', sa.Float(), nullable=True),
    sa.Column('DAM_TYPE', sa.String(), nullable=True),
    sa.Column('INSTREAM', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_features_id'), 'features', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_features_id'), table_name='features')
    op.drop_table('features')
    # ### end Alembic commands ###
