"""empty message

Revision ID: c980f19d9f38
Revises: 2b8e5e5fc2e4
Create Date: 2025-12-06 22:43:22.098207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c980f19d9f38'
down_revision: Union[str, Sequence[str], None] = '2b8e5e5fc2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('water_histories_object_id_fkey'), 'water_histories', type_='foreignkey')
    op.create_foreign_key(None, 'water_histories', 'objects', ['object_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'water_histories', type_='foreignkey')
    op.create_foreign_key(op.f('water_histories_object_id_fkey'), 'water_histories', 'water_classes', ['object_id'], ['id'])
    # ### end Alembic commands ###
