"""empty message

Revision ID: eb07fc92ac73
Revises: 7c1c18368567
Create Date: 2025-12-06 22:39:16.923834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb07fc92ac73'
down_revision: Union[str, Sequence[str], None] = '7c1c18368567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('water_histories', sa.Column('object_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('water_histories_water_class_id_fkey'), 'water_histories', type_='foreignkey')
    op.create_foreign_key(None, 'water_histories', 'water_classes', ['object_id'], ['id'])
    op.drop_column('water_histories', 'water_class_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('water_histories', sa.Column('water_class_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'water_histories', type_='foreignkey')
    op.create_foreign_key(op.f('water_histories_water_class_id_fkey'), 'water_histories', 'water_classes', ['water_class_id'], ['id'])
    op.drop_column('water_histories', 'object_id')
    # ### end Alembic commands ###
