"""empty message

Revision ID: fbbf788ab5e1
Revises: 23b9ff95c605
Create Date: 2025-12-05 17:43:35.670630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbbf788ab5e1'
down_revision: Union[str, Sequence[str], None] = '23b9ff95c605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_id'), 'regions', ['id'], unique=False)
    op.add_column('objects', sa.Column('region_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'objects', 'regions', ['region_id'], ['id'])
    op.drop_column('objects', 'region')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.add_column('objects', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'objects', type_='foreignkey')
    op.drop_column('objects', 'region_id')
    op.drop_index(op.f('ix_regions_id'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
